version: "3.8"

services:

    grpchat:
        container_name: grpchat-frontend
        environment: 
            - APP_ENV=${APP_ENV}
        build: 
            context: ./
            dockerfile: ./docker/Dockerfile
        ports:
            - "3000:3000"
            - "5000:5000"
        stdin_open: true
        restart: on-failure
        volumes: 
            - "./src:/usr/src/grpchat-frontend/src"