version: "3.8"

services:
  db:
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RPCHAT_ADMIN_PASSWORD=${RPCHAT_ADMIN_PASSWORD}
      - PGOPTIONS=${PGOPTIONS}
    image: postgres:alpine
    ports: 
        - "5430:5432"
    restart: on-failure
    volumes:
      - "./db-data:/var/lib/postgresql/data"
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"

  proxy:
      container_name: envoy
      build: 
        context: ./
        dockerfile: ./docker/envoy.Dockerfile
      ports:
        - "443:443"
        - "9901:9901"
      restart: always
    
  grpchat:
    build: 
      context: ./
      dockerfile: ./docker/server.Dockerfile
    container_name: grpchat-server
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}      
      - APP_ENV=${APP_ENV}
    depends_on:
      - db
    ports:
      - "9090:9090"
      - "4430:4430"
    restart: on-failure
    volumes: 
      - "./static/attachments:/usr/src/grpchat-backend/static/attachments"
      - "./:/usr/src/grpchat-backend"