// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type NewMessageRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Memo                 string   `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMessageRequest) Reset()         { *m = NewMessageRequest{} }
func (m *NewMessageRequest) String() string { return proto.CompactTextString(m) }
func (*NewMessageRequest) ProtoMessage()    {}
func (*NewMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *NewMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMessageRequest.Unmarshal(m, b)
}
func (m *NewMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMessageRequest.Marshal(b, m, deterministic)
}
func (m *NewMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMessageRequest.Merge(m, src)
}
func (m *NewMessageRequest) XXX_Size() int {
	return xxx_messageInfo_NewMessageRequest.Size(m)
}
func (m *NewMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewMessageRequest proto.InternalMessageInfo

func (m *NewMessageRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *NewMessageRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *NewMessageRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type NewMessageResponse struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostDate             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=post_date,json=postDate,proto3" json:"post_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NewMessageResponse) Reset()         { *m = NewMessageResponse{} }
func (m *NewMessageResponse) String() string { return proto.CompactTextString(m) }
func (*NewMessageResponse) ProtoMessage()    {}
func (*NewMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *NewMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMessageResponse.Unmarshal(m, b)
}
func (m *NewMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMessageResponse.Marshal(b, m, deterministic)
}
func (m *NewMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMessageResponse.Merge(m, src)
}
func (m *NewMessageResponse) XXX_Size() int {
	return xxx_messageInfo_NewMessageResponse.Size(m)
}
func (m *NewMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewMessageResponse proto.InternalMessageInfo

func (m *NewMessageResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NewMessageResponse) GetPostDate() *timestamp.Timestamp {
	if m != nil {
		return m.PostDate
	}
	return nil
}

type EditMessageRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Memo                 string   `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMessageRequest) Reset()         { *m = EditMessageRequest{} }
func (m *EditMessageRequest) String() string { return proto.CompactTextString(m) }
func (*EditMessageRequest) ProtoMessage()    {}
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *EditMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMessageRequest.Unmarshal(m, b)
}
func (m *EditMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMessageRequest.Marshal(b, m, deterministic)
}
func (m *EditMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMessageRequest.Merge(m, src)
}
func (m *EditMessageRequest) XXX_Size() int {
	return xxx_messageInfo_EditMessageRequest.Size(m)
}
func (m *EditMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditMessageRequest proto.InternalMessageInfo

func (m *EditMessageRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditMessageRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type NewChannelRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewChannelRequest) Reset()         { *m = NewChannelRequest{} }
func (m *NewChannelRequest) String() string { return proto.CompactTextString(m) }
func (*NewChannelRequest) ProtoMessage()    {}
func (*NewChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *NewChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewChannelRequest.Unmarshal(m, b)
}
func (m *NewChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewChannelRequest.Marshal(b, m, deterministic)
}
func (m *NewChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewChannelRequest.Merge(m, src)
}
func (m *NewChannelRequest) XXX_Size() int {
	return xxx_messageInfo_NewChannelRequest.Size(m)
}
func (m *NewChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewChannelRequest proto.InternalMessageInfo

func (m *NewChannelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewChannelRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NewChannelRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type EditChannelRequest struct {
	OldName              string   `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName              string   `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditChannelRequest) Reset()         { *m = EditChannelRequest{} }
func (m *EditChannelRequest) String() string { return proto.CompactTextString(m) }
func (*EditChannelRequest) ProtoMessage()    {}
func (*EditChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *EditChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditChannelRequest.Unmarshal(m, b)
}
func (m *EditChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditChannelRequest.Marshal(b, m, deterministic)
}
func (m *EditChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditChannelRequest.Merge(m, src)
}
func (m *EditChannelRequest) XXX_Size() int {
	return xxx_messageInfo_EditChannelRequest.Size(m)
}
func (m *EditChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditChannelRequest proto.InternalMessageInfo

func (m *EditChannelRequest) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

func (m *EditChannelRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

func (m *EditChannelRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type NewUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ImagePath            string   `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewUserRequest) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

type EditUserRequest struct {
	OldName              string   `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OldPassword          string   `protobuf:"bytes,4,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditUserRequest) Reset()         { *m = EditUserRequest{} }
func (m *EditUserRequest) String() string { return proto.CompactTextString(m) }
func (*EditUserRequest) ProtoMessage()    {}
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *EditUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserRequest.Unmarshal(m, b)
}
func (m *EditUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserRequest.Marshal(b, m, deterministic)
}
func (m *EditUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserRequest.Merge(m, src)
}
func (m *EditUserRequest) XXX_Size() int {
	return xxx_messageInfo_EditUserRequest.Size(m)
}
func (m *EditUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserRequest proto.InternalMessageInfo

func (m *EditUserRequest) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

func (m *EditUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EditUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditUserRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *EditUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type BroadcastMessage struct {
	ChatMessage          *NewMessageRequest `protobuf:"bytes,1,opt,name=chat_message,json=chatMessage,proto3" json:"chat_message,omitempty"`
	Channel              *NewChannelRequest `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	User                 *NewUserRequest    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BroadcastMessage) Reset()         { *m = BroadcastMessage{} }
func (m *BroadcastMessage) String() string { return proto.CompactTextString(m) }
func (*BroadcastMessage) ProtoMessage()    {}
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{8}
}

func (m *BroadcastMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastMessage.Unmarshal(m, b)
}
func (m *BroadcastMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastMessage.Marshal(b, m, deterministic)
}
func (m *BroadcastMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastMessage.Merge(m, src)
}
func (m *BroadcastMessage) XXX_Size() int {
	return xxx_messageInfo_BroadcastMessage.Size(m)
}
func (m *BroadcastMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastMessage proto.InternalMessageInfo

func (m *BroadcastMessage) GetChatMessage() *NewMessageRequest {
	if m != nil {
		return m.ChatMessage
	}
	return nil
}

func (m *BroadcastMessage) GetChannel() *NewChannelRequest {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *BroadcastMessage) GetUser() *NewUserRequest {
	if m != nil {
		return m.User
	}
	return nil
}

type GetChannelsMessage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChannelsMessage) Reset()         { *m = GetChannelsMessage{} }
func (m *GetChannelsMessage) String() string { return proto.CompactTextString(m) }
func (*GetChannelsMessage) ProtoMessage()    {}
func (*GetChannelsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{9}
}

func (m *GetChannelsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannelsMessage.Unmarshal(m, b)
}
func (m *GetChannelsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannelsMessage.Marshal(b, m, deterministic)
}
func (m *GetChannelsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannelsMessage.Merge(m, src)
}
func (m *GetChannelsMessage) XXX_Size() int {
	return xxx_messageInfo_GetChannelsMessage.Size(m)
}
func (m *GetChannelsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannelsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannelsMessage proto.InternalMessageInfo

func (m *GetChannelsMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetChannelsMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetChannelsMessage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetChannelsMessage) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type GetChannelsResponse struct {
	Channels             []*GetChannelsMessage `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetChannelsResponse) Reset()         { *m = GetChannelsResponse{} }
func (m *GetChannelsResponse) String() string { return proto.CompactTextString(m) }
func (*GetChannelsResponse) ProtoMessage()    {}
func (*GetChannelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{10}
}

func (m *GetChannelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannelsResponse.Unmarshal(m, b)
}
func (m *GetChannelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannelsResponse.Marshal(b, m, deterministic)
}
func (m *GetChannelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannelsResponse.Merge(m, src)
}
func (m *GetChannelsResponse) XXX_Size() int {
	return xxx_messageInfo_GetChannelsResponse.Size(m)
}
func (m *GetChannelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannelsResponse proto.InternalMessageInfo

func (m *GetChannelsResponse) GetChannels() []*GetChannelsMessage {
	if m != nil {
		return m.Channels
	}
	return nil
}

type GetUsersMessage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersMessage) Reset()         { *m = GetUsersMessage{} }
func (m *GetUsersMessage) String() string { return proto.CompactTextString(m) }
func (*GetUsersMessage) ProtoMessage()    {}
func (*GetUsersMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{11}
}

func (m *GetUsersMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersMessage.Unmarshal(m, b)
}
func (m *GetUsersMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersMessage.Marshal(b, m, deterministic)
}
func (m *GetUsersMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersMessage.Merge(m, src)
}
func (m *GetUsersMessage) XXX_Size() int {
	return xxx_messageInfo_GetUsersMessage.Size(m)
}
func (m *GetUsersMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersMessage proto.InternalMessageInfo

func (m *GetUsersMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUsersMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUsersMessage) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type GetUsersResponse struct {
	Users                []*GetUsersMessage `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{12}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() []*GetUsersMessage {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetMessagesRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{13}
}

func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (m *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(m, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

func (m *GetMessagesRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type GetMessagesMessage struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Memo                 string               `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Channel              string               `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	User                 string               `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Avatar               string               `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetMessagesMessage) Reset()         { *m = GetMessagesMessage{} }
func (m *GetMessagesMessage) String() string { return proto.CompactTextString(m) }
func (*GetMessagesMessage) ProtoMessage()    {}
func (*GetMessagesMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{14}
}

func (m *GetMessagesMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesMessage.Unmarshal(m, b)
}
func (m *GetMessagesMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesMessage.Marshal(b, m, deterministic)
}
func (m *GetMessagesMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesMessage.Merge(m, src)
}
func (m *GetMessagesMessage) XXX_Size() int {
	return xxx_messageInfo_GetMessagesMessage.Size(m)
}
func (m *GetMessagesMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesMessage proto.InternalMessageInfo

func (m *GetMessagesMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetMessagesMessage) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *GetMessagesMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *GetMessagesMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GetMessagesMessage) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *GetMessagesMessage) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type GetMessagesResponse struct {
	Messages             []*GetMessagesMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetMessagesResponse) Reset()         { *m = GetMessagesResponse{} }
func (m *GetMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessagesResponse) ProtoMessage()    {}
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{15}
}

func (m *GetMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesResponse.Unmarshal(m, b)
}
func (m *GetMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesResponse.Marshal(b, m, deterministic)
}
func (m *GetMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesResponse.Merge(m, src)
}
func (m *GetMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessagesResponse.Size(m)
}
func (m *GetMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesResponse proto.InternalMessageInfo

func (m *GetMessagesResponse) GetMessages() []*GetMessagesMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "chat.EmptyMessage")
	proto.RegisterType((*NewMessageRequest)(nil), "chat.NewMessageRequest")
	proto.RegisterType((*NewMessageResponse)(nil), "chat.NewMessageResponse")
	proto.RegisterType((*EditMessageRequest)(nil), "chat.EditMessageRequest")
	proto.RegisterType((*NewChannelRequest)(nil), "chat.NewChannelRequest")
	proto.RegisterType((*EditChannelRequest)(nil), "chat.EditChannelRequest")
	proto.RegisterType((*NewUserRequest)(nil), "chat.NewUserRequest")
	proto.RegisterType((*EditUserRequest)(nil), "chat.EditUserRequest")
	proto.RegisterType((*BroadcastMessage)(nil), "chat.BroadcastMessage")
	proto.RegisterType((*GetChannelsMessage)(nil), "chat.GetChannelsMessage")
	proto.RegisterType((*GetChannelsResponse)(nil), "chat.GetChannelsResponse")
	proto.RegisterType((*GetUsersMessage)(nil), "chat.GetUsersMessage")
	proto.RegisterType((*GetUsersResponse)(nil), "chat.GetUsersResponse")
	proto.RegisterType((*GetMessagesRequest)(nil), "chat.GetMessagesRequest")
	proto.RegisterType((*GetMessagesMessage)(nil), "chat.GetMessagesMessage")
	proto.RegisterType((*GetMessagesResponse)(nil), "chat.GetMessagesResponse")
}

func init() {
	proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54)
}

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0x9a, 0x76, 0x6b, 0x6f, 0xa6, 0x6d, 0x98, 0x31, 0xd2, 0x4a, 0x88, 0x91, 0xa7, 0x4a,
	0x48, 0x1d, 0x14, 0x04, 0x1b, 0x20, 0x4d, 0x6c, 0x4c, 0x7b, 0x40, 0xab, 0xa6, 0xc0, 0x1e, 0x51,
	0xe5, 0x35, 0xa6, 0x8d, 0x94, 0xc4, 0x21, 0x76, 0x57, 0xf1, 0x21, 0x7c, 0x05, 0x3f, 0xc0, 0xa7,
	0xf1, 0x88, 0x62, 0xc7, 0xae, 0xdb, 0x64, 0xd1, 0x78, 0x8b, 0xaf, 0xaf, 0xef, 0x39, 0xe7, 0xfa,
	0x5c, 0x07, 0x60, 0x32, 0xc3, 0x7c, 0x90, 0x66, 0x94, 0x53, 0xd4, 0xcc, 0xbf, 0x7b, 0x4f, 0xa7,
	0x94, 0x4e, 0x23, 0x72, 0x28, 0x62, 0x37, 0xf3, 0xef, 0x87, 0x3c, 0x8c, 0x09, 0xe3, 0x38, 0x4e,
	0x65, 0x9a, 0xb7, 0x0d, 0x5b, 0xe7, 0x71, 0xca, 0x7f, 0x5e, 0x12, 0xc6, 0xf0, 0x94, 0x78, 0xd7,
	0xf0, 0x60, 0x44, 0x16, 0xc5, 0xca, 0x27, 0x3f, 0xe6, 0x84, 0x71, 0x84, 0xa0, 0x39, 0x67, 0x24,
	0x73, 0xad, 0x03, 0xab, 0xdf, 0xf1, 0xc5, 0x77, 0x1e, 0x8b, 0x49, 0x4c, 0xdd, 0x86, 0x8c, 0xe5,
	0xdf, 0xc8, 0x85, 0xcd, 0xc9, 0x0c, 0x27, 0x09, 0x89, 0x5c, 0x5b, 0x84, 0xd5, 0xd2, 0xfb, 0x06,
	0xc8, 0x2c, 0xcb, 0x52, 0x9a, 0x30, 0x82, 0xb6, 0xa1, 0x11, 0x06, 0xa2, 0x6a, 0xcb, 0x6f, 0x84,
	0x01, 0x7a, 0x0b, 0x9d, 0x94, 0x32, 0x3e, 0x0e, 0x30, 0x27, 0xa2, 0xb0, 0x33, 0xec, 0x0d, 0xa4,
	0x82, 0x81, 0x52, 0x30, 0xf8, 0xaa, 0x14, 0xf8, 0xed, 0x3c, 0xf9, 0x13, 0xe6, 0xc4, 0x3b, 0x02,
	0x74, 0x1e, 0x84, 0x7c, 0x8d, 0xf6, 0x7a, 0xf9, 0x0a, 0xca, 0xde, 0x58, 0xe8, 0x3d, 0x93, 0x34,
	0x0d, 0xbd, 0x09, 0x8e, 0x89, 0xd2, 0x9b, 0x7f, 0xa3, 0x03, 0x70, 0x02, 0xc2, 0x26, 0x59, 0x98,
	0xf2, 0x90, 0x26, 0x45, 0x0d, 0x33, 0x84, 0xf6, 0xa0, 0x45, 0x17, 0x09, 0xc9, 0x0a, 0xed, 0x72,
	0xe1, 0x45, 0x92, 0xda, 0x1a, 0x42, 0x17, 0xda, 0x34, 0x0a, 0xc6, 0x06, 0xca, 0x26, 0x8d, 0x82,
	0x51, 0x0e, 0xd4, 0x85, 0x76, 0x42, 0x16, 0x72, 0x4b, 0xa2, 0x6c, 0x26, 0x64, 0x31, 0xaa, 0xe0,
	0x60, 0x97, 0x38, 0x78, 0x73, 0xd8, 0x1e, 0x91, 0xc5, 0x35, 0x23, 0x59, 0x9d, 0x96, 0x3d, 0x68,
	0x91, 0x18, 0x87, 0x51, 0x51, 0x5f, 0x2e, 0x50, 0x0f, 0xda, 0x29, 0x66, 0x6c, 0x41, 0xb3, 0xa0,
	0x28, 0xad, 0xd7, 0xe8, 0x09, 0x40, 0x18, 0xe3, 0x29, 0x19, 0xa7, 0x98, 0xcf, 0xdc, 0xa6, 0xd8,
	0xed, 0x88, 0xc8, 0x15, 0xe6, 0x33, 0xef, 0x97, 0x05, 0x3b, 0xb9, 0x4a, 0x13, 0xb8, 0x46, 0x62,
	0x35, 0xbe, 0x62, 0x6a, 0x1b, 0x4c, 0x9f, 0xc1, 0x56, 0x5e, 0x44, 0xf3, 0x92, 0xc8, 0x0e, 0x8d,
	0x82, 0x2b, 0x45, 0xcd, 0xa4, 0xdd, 0x5a, 0xa5, 0xed, 0xfd, 0xb6, 0x60, 0xf7, 0x34, 0xa3, 0x38,
	0x98, 0x60, 0xa6, 0xdc, 0x81, 0xde, 0xc1, 0x56, 0x3e, 0x1b, 0xe3, 0x58, 0xae, 0x05, 0x39, 0x67,
	0xf8, 0x78, 0x20, 0x86, 0xa7, 0x64, 0x7e, 0xdf, 0xc9, 0xe3, 0xea, 0xec, 0xcb, 0xa5, 0xc3, 0x1b,
	0x6b, 0xc7, 0x56, 0x6f, 0x58, 0x5b, 0x1f, 0xf5, 0x8b, 0xe1, 0xb1, 0x45, 0xfe, 0x9e, 0xce, 0x37,
	0x7a, 0x25, 0x47, 0xca, 0x4b, 0x01, 0x5d, 0x10, 0xe5, 0x14, 0xa6, 0x20, 0x2b, 0x5c, 0x6c, 0x78,
	0xa3, 0xd2, 0x9c, 0x76, 0x8d, 0x39, 0x9b, 0xa6, 0x39, 0x3f, 0xc3, 0x43, 0x03, 0x51, 0xcf, 0xe5,
	0x6b, 0x68, 0x17, 0xec, 0x99, 0x6b, 0x1d, 0xd8, 0x7d, 0x67, 0xe8, 0x4a, 0xda, 0x65, 0x7a, 0xbe,
	0xce, 0xf4, 0x2e, 0x61, 0xe7, 0x82, 0x08, 0x0b, 0xfc, 0x17, 0xf7, 0x7d, 0xd8, 0xc0, 0xb7, 0x98,
	0x63, 0x35, 0x37, 0xc5, 0xca, 0x3b, 0x81, 0x5d, 0x55, 0x4e, 0x13, 0x7b, 0x0e, 0xad, 0xbc, 0x53,
	0x8a, 0xd5, 0x23, 0xcd, 0xca, 0x44, 0xf5, 0x65, 0x8e, 0x37, 0x10, 0xed, 0x2c, 0x82, 0x4c, 0xd9,
	0xd2, 0x78, 0xa3, 0xac, 0xd5, 0x37, 0xea, 0x8f, 0xb5, 0x72, 0xa0, 0x46, 0xc3, 0xfd, 0x1f, 0x3e,
	0x74, 0x04, 0x1d, 0xfd, 0xe4, 0x8a, 0xde, 0xd7, 0x3f, 0x69, 0xcb, 0x64, 0xfd, 0xe8, 0xb6, 0x8c,
	0x47, 0x77, 0xd9, 0xab, 0x8d, 0x95, 0x5e, 0xc9, 0x7b, 0x5c, 0x4a, 0x5d, 0xde, 0x63, 0x61, 0xf2,
	0xf2, 0x3d, 0xae, 0xc9, 0xf4, 0x75, 0xe6, 0xf0, 0xaf, 0x0d, 0xce, 0xd9, 0x0c, 0xf3, 0x2f, 0x24,
	0xbb, 0x0d, 0x27, 0x04, 0x1d, 0x43, 0x47, 0xcf, 0x10, 0x42, 0xb2, 0x80, 0xf9, 0xcf, 0xe8, 0xed,
	0xcb, 0xd8, 0xfa, 0xa0, 0xbd, 0xb0, 0xd0, 0x09, 0xc0, 0xc7, 0x20, 0x50, 0x9d, 0xbc, 0x6b, 0xc4,
	0x7a, 0x6e, 0x79, 0xa3, 0x50, 0x70, 0x2c, 0x0a, 0x14, 0x9e, 0x43, 0x77, 0x0d, 0x5b, 0xaf, 0x82,
	0x15, 0x7a, 0x0f, 0x8e, 0xf1, 0x4f, 0x40, 0x05, 0x46, 0xf9, 0x37, 0x51, 0x77, 0x58, 0x01, 0x1b,
	0x87, 0xef, 0x81, 0xfc, 0x01, 0x1c, 0x63, 0x50, 0x2a, 0x5b, 0xd6, 0x2d, 0xcd, 0x93, 0x96, 0xfc,
	0x06, 0xda, 0xca, 0xd0, 0x75, 0xdd, 0x2e, 0xcd, 0xc6, 0xa9, 0x40, 0x55, 0xd7, 0x8a, 0xca, 0x37,
	0xad, 0x28, 0x77, 0x2b, 0x76, 0x64, 0x8d, 0x9b, 0x0d, 0x61, 0xc9, 0x57, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x93, 0x4d, 0x8e, 0xee, 0x49, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	// broadcast
	Broadcast(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (ChatService_BroadcastClient, error)
	// add new object
	AddMessage(ctx context.Context, in *NewMessageRequest, opts ...grpc.CallOption) (*NewMessageResponse, error)
	AddChannel(ctx context.Context, in *NewChannelRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	// edit object
	EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	EditChannel(ctx context.Context, in *EditChannelRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	// get object
	GetChannels(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetChannelsResponse, error)
	GetUsers(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetUsersResponse, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Broadcast(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (ChatService_BroadcastClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatService_serviceDesc.Streams[0], "/chat.ChatService/Broadcast", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceBroadcastClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_BroadcastClient interface {
	Recv() (*BroadcastMessage, error)
	grpc.ClientStream
}

type chatServiceBroadcastClient struct {
	grpc.ClientStream
}

func (x *chatServiceBroadcastClient) Recv() (*BroadcastMessage, error) {
	m := new(BroadcastMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) AddMessage(ctx context.Context, in *NewMessageRequest, opts ...grpc.CallOption) (*NewMessageResponse, error) {
	out := new(NewMessageResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatService/AddMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) AddChannel(ctx context.Context, in *NewChannelRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/chat.ChatService/AddChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/chat.ChatService/EditMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) EditChannel(ctx context.Context, in *EditChannelRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/chat.ChatService/EditChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetChannels(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetChannelsResponse, error) {
	out := new(GetChannelsResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatService/GetChannels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetUsers(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatService/GetMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	// broadcast
	Broadcast(*EmptyMessage, ChatService_BroadcastServer) error
	// add new object
	AddMessage(context.Context, *NewMessageRequest) (*NewMessageResponse, error)
	AddChannel(context.Context, *NewChannelRequest) (*EmptyMessage, error)
	// edit object
	EditMessage(context.Context, *EditMessageRequest) (*EmptyMessage, error)
	EditChannel(context.Context, *EditChannelRequest) (*EmptyMessage, error)
	// get object
	GetChannels(context.Context, *EmptyMessage) (*GetChannelsResponse, error)
	GetUsers(context.Context, *EmptyMessage) (*GetUsersResponse, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) Broadcast(req *EmptyMessage, srv ChatService_BroadcastServer) error {
	return status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (*UnimplementedChatServiceServer) AddMessage(ctx context.Context, req *NewMessageRequest) (*NewMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMessage not implemented")
}
func (*UnimplementedChatServiceServer) AddChannel(ctx context.Context, req *NewChannelRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChannel not implemented")
}
func (*UnimplementedChatServiceServer) EditMessage(ctx context.Context, req *EditMessageRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditMessage not implemented")
}
func (*UnimplementedChatServiceServer) EditChannel(ctx context.Context, req *EditChannelRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditChannel not implemented")
}
func (*UnimplementedChatServiceServer) GetChannels(ctx context.Context, req *EmptyMessage) (*GetChannelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannels not implemented")
}
func (*UnimplementedChatServiceServer) GetUsers(ctx context.Context, req *EmptyMessage) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedChatServiceServer) GetMessages(ctx context.Context, req *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Broadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).Broadcast(m, &chatServiceBroadcastServer{stream})
}

type ChatService_BroadcastServer interface {
	Send(*BroadcastMessage) error
	grpc.ServerStream
}

type chatServiceBroadcastServer struct {
	grpc.ServerStream
}

func (x *chatServiceBroadcastServer) Send(m *BroadcastMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/AddMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AddMessage(ctx, req.(*NewMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_AddChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AddChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/AddChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AddChannel(ctx, req.(*NewChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_EditMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).EditMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/EditMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).EditMessage(ctx, req.(*EditMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_EditChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).EditChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/EditChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).EditChannel(ctx, req.(*EditChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetChannels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetChannels(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetUsers(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMessage",
			Handler:    _ChatService_AddMessage_Handler,
		},
		{
			MethodName: "AddChannel",
			Handler:    _ChatService_AddChannel_Handler,
		},
		{
			MethodName: "EditMessage",
			Handler:    _ChatService_EditMessage_Handler,
		},
		{
			MethodName: "EditChannel",
			Handler:    _ChatService_EditChannel_Handler,
		},
		{
			MethodName: "GetChannels",
			Handler:    _ChatService_GetChannels_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _ChatService_GetUsers_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _ChatService_GetMessages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Broadcast",
			Handler:       _ChatService_Broadcast_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}
