// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type NewMessageRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Memo                 string   `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMessageRequest) Reset()         { *m = NewMessageRequest{} }
func (m *NewMessageRequest) String() string { return proto.CompactTextString(m) }
func (*NewMessageRequest) ProtoMessage()    {}
func (*NewMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *NewMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMessageRequest.Unmarshal(m, b)
}
func (m *NewMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMessageRequest.Marshal(b, m, deterministic)
}
func (m *NewMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMessageRequest.Merge(m, src)
}
func (m *NewMessageRequest) XXX_Size() int {
	return xxx_messageInfo_NewMessageRequest.Size(m)
}
func (m *NewMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewMessageRequest proto.InternalMessageInfo

func (m *NewMessageRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *NewMessageRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *NewMessageRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type EditMessageRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Memo                 string   `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Edited               bool     `protobuf:"varint,3,opt,name=edited,proto3" json:"edited,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMessageRequest) Reset()         { *m = EditMessageRequest{} }
func (m *EditMessageRequest) String() string { return proto.CompactTextString(m) }
func (*EditMessageRequest) ProtoMessage()    {}
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *EditMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMessageRequest.Unmarshal(m, b)
}
func (m *EditMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMessageRequest.Marshal(b, m, deterministic)
}
func (m *EditMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMessageRequest.Merge(m, src)
}
func (m *EditMessageRequest) XXX_Size() int {
	return xxx_messageInfo_EditMessageRequest.Size(m)
}
func (m *EditMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditMessageRequest proto.InternalMessageInfo

func (m *EditMessageRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditMessageRequest) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *EditMessageRequest) GetEdited() bool {
	if m != nil {
		return m.Edited
	}
	return false
}

type NewChannelRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewChannelRequest) Reset()         { *m = NewChannelRequest{} }
func (m *NewChannelRequest) String() string { return proto.CompactTextString(m) }
func (*NewChannelRequest) ProtoMessage()    {}
func (*NewChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *NewChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewChannelRequest.Unmarshal(m, b)
}
func (m *NewChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewChannelRequest.Marshal(b, m, deterministic)
}
func (m *NewChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewChannelRequest.Merge(m, src)
}
func (m *NewChannelRequest) XXX_Size() int {
	return xxx_messageInfo_NewChannelRequest.Size(m)
}
func (m *NewChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewChannelRequest proto.InternalMessageInfo

func (m *NewChannelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewChannelRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NewChannelRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type EditChannelRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditChannelRequest) Reset()         { *m = EditChannelRequest{} }
func (m *EditChannelRequest) String() string { return proto.CompactTextString(m) }
func (*EditChannelRequest) ProtoMessage()    {}
func (*EditChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *EditChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditChannelRequest.Unmarshal(m, b)
}
func (m *EditChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditChannelRequest.Marshal(b, m, deterministic)
}
func (m *EditChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditChannelRequest.Merge(m, src)
}
func (m *EditChannelRequest) XXX_Size() int {
	return xxx_messageInfo_EditChannelRequest.Size(m)
}
func (m *EditChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditChannelRequest proto.InternalMessageInfo

func (m *EditChannelRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditChannelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditChannelRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditChannelRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type NewUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ImagePath            string   `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewUserRequest) GetImagePath() string {
	if m != nil {
		return m.ImagePath
	}
	return ""
}

type EditUserRequest struct {
	OldName              string   `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OldPassword          string   `protobuf:"bytes,4,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditUserRequest) Reset()         { *m = EditUserRequest{} }
func (m *EditUserRequest) String() string { return proto.CompactTextString(m) }
func (*EditUserRequest) ProtoMessage()    {}
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *EditUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserRequest.Unmarshal(m, b)
}
func (m *EditUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserRequest.Marshal(b, m, deterministic)
}
func (m *EditUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserRequest.Merge(m, src)
}
func (m *EditUserRequest) XXX_Size() int {
	return xxx_messageInfo_EditUserRequest.Size(m)
}
func (m *EditUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserRequest proto.InternalMessageInfo

func (m *EditUserRequest) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

func (m *EditUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EditUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditUserRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *EditUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetChannelsMessage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChannelsMessage) Reset()         { *m = GetChannelsMessage{} }
func (m *GetChannelsMessage) String() string { return proto.CompactTextString(m) }
func (*GetChannelsMessage) ProtoMessage()    {}
func (*GetChannelsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *GetChannelsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannelsMessage.Unmarshal(m, b)
}
func (m *GetChannelsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannelsMessage.Marshal(b, m, deterministic)
}
func (m *GetChannelsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannelsMessage.Merge(m, src)
}
func (m *GetChannelsMessage) XXX_Size() int {
	return xxx_messageInfo_GetChannelsMessage.Size(m)
}
func (m *GetChannelsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannelsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannelsMessage proto.InternalMessageInfo

func (m *GetChannelsMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetChannelsMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetChannelsMessage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetChannelsMessage) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type GetChannelsResponse struct {
	Channels             []*GetChannelsMessage `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetChannelsResponse) Reset()         { *m = GetChannelsResponse{} }
func (m *GetChannelsResponse) String() string { return proto.CompactTextString(m) }
func (*GetChannelsResponse) ProtoMessage()    {}
func (*GetChannelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{8}
}

func (m *GetChannelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannelsResponse.Unmarshal(m, b)
}
func (m *GetChannelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannelsResponse.Marshal(b, m, deterministic)
}
func (m *GetChannelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannelsResponse.Merge(m, src)
}
func (m *GetChannelsResponse) XXX_Size() int {
	return xxx_messageInfo_GetChannelsResponse.Size(m)
}
func (m *GetChannelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannelsResponse proto.InternalMessageInfo

func (m *GetChannelsResponse) GetChannels() []*GetChannelsMessage {
	if m != nil {
		return m.Channels
	}
	return nil
}

type GetUsersMessage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersMessage) Reset()         { *m = GetUsersMessage{} }
func (m *GetUsersMessage) String() string { return proto.CompactTextString(m) }
func (*GetUsersMessage) ProtoMessage()    {}
func (*GetUsersMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{9}
}

func (m *GetUsersMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersMessage.Unmarshal(m, b)
}
func (m *GetUsersMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersMessage.Marshal(b, m, deterministic)
}
func (m *GetUsersMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersMessage.Merge(m, src)
}
func (m *GetUsersMessage) XXX_Size() int {
	return xxx_messageInfo_GetUsersMessage.Size(m)
}
func (m *GetUsersMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersMessage proto.InternalMessageInfo

func (m *GetUsersMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUsersMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUsersMessage) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type GetUsersResponse struct {
	Users                []*GetUsersMessage `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{10}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() []*GetUsersMessage {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetMessagesRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{11}
}

func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (m *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(m, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

func (m *GetMessagesRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type GetFilteredMessagesRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	MinId                int32    `protobuf:"varint,2,opt,name=min_id,json=minId,proto3" json:"min_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilteredMessagesRequest) Reset()         { *m = GetFilteredMessagesRequest{} }
func (m *GetFilteredMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetFilteredMessagesRequest) ProtoMessage()    {}
func (*GetFilteredMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{12}
}

func (m *GetFilteredMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilteredMessagesRequest.Unmarshal(m, b)
}
func (m *GetFilteredMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilteredMessagesRequest.Marshal(b, m, deterministic)
}
func (m *GetFilteredMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilteredMessagesRequest.Merge(m, src)
}
func (m *GetFilteredMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetFilteredMessagesRequest.Size(m)
}
func (m *GetFilteredMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilteredMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilteredMessagesRequest proto.InternalMessageInfo

func (m *GetFilteredMessagesRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *GetFilteredMessagesRequest) GetMinId() int32 {
	if m != nil {
		return m.MinId
	}
	return 0
}

type GetMessagesMessage struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Memo                 string               `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	Channel              string               `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	User                 string               `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Avatar               string               `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Edited               bool                 `protobuf:"varint,7,opt,name=edited,proto3" json:"edited,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetMessagesMessage) Reset()         { *m = GetMessagesMessage{} }
func (m *GetMessagesMessage) String() string { return proto.CompactTextString(m) }
func (*GetMessagesMessage) ProtoMessage()    {}
func (*GetMessagesMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{13}
}

func (m *GetMessagesMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesMessage.Unmarshal(m, b)
}
func (m *GetMessagesMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesMessage.Marshal(b, m, deterministic)
}
func (m *GetMessagesMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesMessage.Merge(m, src)
}
func (m *GetMessagesMessage) XXX_Size() int {
	return xxx_messageInfo_GetMessagesMessage.Size(m)
}
func (m *GetMessagesMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesMessage proto.InternalMessageInfo

func (m *GetMessagesMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetMessagesMessage) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *GetMessagesMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *GetMessagesMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GetMessagesMessage) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *GetMessagesMessage) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GetMessagesMessage) GetEdited() bool {
	if m != nil {
		return m.Edited
	}
	return false
}

type GetMessagesResponse struct {
	Messages             []*GetMessagesMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	MinId                int32                 `protobuf:"varint,2,opt,name=min_id,json=minId,proto3" json:"min_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetMessagesResponse) Reset()         { *m = GetMessagesResponse{} }
func (m *GetMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessagesResponse) ProtoMessage()    {}
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{14}
}

func (m *GetMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesResponse.Unmarshal(m, b)
}
func (m *GetMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesResponse.Marshal(b, m, deterministic)
}
func (m *GetMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesResponse.Merge(m, src)
}
func (m *GetMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessagesResponse.Size(m)
}
func (m *GetMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesResponse proto.InternalMessageInfo

func (m *GetMessagesResponse) GetMessages() []*GetMessagesMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *GetMessagesResponse) GetMinId() int32 {
	if m != nil {
		return m.MinId
	}
	return 0
}

type BroadcastRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRequest) Reset()         { *m = BroadcastRequest{} }
func (m *BroadcastRequest) String() string { return proto.CompactTextString(m) }
func (*BroadcastRequest) ProtoMessage()    {}
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{15}
}

func (m *BroadcastRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRequest.Unmarshal(m, b)
}
func (m *BroadcastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRequest.Marshal(b, m, deterministic)
}
func (m *BroadcastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRequest.Merge(m, src)
}
func (m *BroadcastRequest) XXX_Size() int {
	return xxx_messageInfo_BroadcastRequest.Size(m)
}
func (m *BroadcastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRequest proto.InternalMessageInfo

func (m *BroadcastRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type BroadcastResponse struct {
	ChatMessage          *GetMessagesMessage `protobuf:"bytes,1,opt,name=chat_message,json=chatMessage,proto3" json:"chat_message,omitempty"`
	Channel              *GetChannelsMessage `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	User                 *GetUsersMessage    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Users                *GetUsersResponse   `protobuf:"bytes,4,opt,name=users,proto3" json:"users,omitempty"`
	ChatMessageEdit      *EditMessageRequest `protobuf:"bytes,5,opt,name=chat_message_edit,json=chatMessageEdit,proto3" json:"chat_message_edit,omitempty"`
	ChannelEdit          *EditChannelRequest `protobuf:"bytes,6,opt,name=channel_edit,json=channelEdit,proto3" json:"channel_edit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BroadcastResponse) Reset()         { *m = BroadcastResponse{} }
func (m *BroadcastResponse) String() string { return proto.CompactTextString(m) }
func (*BroadcastResponse) ProtoMessage()    {}
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{16}
}

func (m *BroadcastResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastResponse.Unmarshal(m, b)
}
func (m *BroadcastResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastResponse.Marshal(b, m, deterministic)
}
func (m *BroadcastResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastResponse.Merge(m, src)
}
func (m *BroadcastResponse) XXX_Size() int {
	return xxx_messageInfo_BroadcastResponse.Size(m)
}
func (m *BroadcastResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastResponse proto.InternalMessageInfo

func (m *BroadcastResponse) GetChatMessage() *GetMessagesMessage {
	if m != nil {
		return m.ChatMessage
	}
	return nil
}

func (m *BroadcastResponse) GetChannel() *GetChannelsMessage {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *BroadcastResponse) GetUser() *GetUsersMessage {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BroadcastResponse) GetUsers() *GetUsersResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *BroadcastResponse) GetChatMessageEdit() *EditMessageRequest {
	if m != nil {
		return m.ChatMessageEdit
	}
	return nil
}

func (m *BroadcastResponse) GetChannelEdit() *EditChannelRequest {
	if m != nil {
		return m.ChannelEdit
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "chat.EmptyMessage")
	proto.RegisterType((*NewMessageRequest)(nil), "chat.NewMessageRequest")
	proto.RegisterType((*EditMessageRequest)(nil), "chat.EditMessageRequest")
	proto.RegisterType((*NewChannelRequest)(nil), "chat.NewChannelRequest")
	proto.RegisterType((*EditChannelRequest)(nil), "chat.EditChannelRequest")
	proto.RegisterType((*NewUserRequest)(nil), "chat.NewUserRequest")
	proto.RegisterType((*EditUserRequest)(nil), "chat.EditUserRequest")
	proto.RegisterType((*GetChannelsMessage)(nil), "chat.GetChannelsMessage")
	proto.RegisterType((*GetChannelsResponse)(nil), "chat.GetChannelsResponse")
	proto.RegisterType((*GetUsersMessage)(nil), "chat.GetUsersMessage")
	proto.RegisterType((*GetUsersResponse)(nil), "chat.GetUsersResponse")
	proto.RegisterType((*GetMessagesRequest)(nil), "chat.GetMessagesRequest")
	proto.RegisterType((*GetFilteredMessagesRequest)(nil), "chat.GetFilteredMessagesRequest")
	proto.RegisterType((*GetMessagesMessage)(nil), "chat.GetMessagesMessage")
	proto.RegisterType((*GetMessagesResponse)(nil), "chat.GetMessagesResponse")
	proto.RegisterType((*BroadcastRequest)(nil), "chat.BroadcastRequest")
	proto.RegisterType((*BroadcastResponse)(nil), "chat.BroadcastResponse")
}

func init() {
	proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54)
}

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 808 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0xdb, 0xa5, 0x6b, 0x4f, 0xa6, 0x6e, 0x33, 0xdb, 0xe8, 0x2a, 0x21, 0x4a, 0xae, 0x86,
	0x40, 0x1d, 0x2a, 0x08, 0x81, 0x36, 0x81, 0xd8, 0x18, 0x13, 0x42, 0x9b, 0xa6, 0xc0, 0xae, 0x2b,
	0xaf, 0x39, 0xb4, 0x91, 0xf2, 0x47, 0xec, 0xae, 0xe2, 0x11, 0x78, 0x00, 0xde, 0x8b, 0x47, 0xe0,
	0x51, 0x90, 0x1d, 0x3b, 0x75, 0xd3, 0xa6, 0x8c, 0x0b, 0xee, 0xe2, 0x63, 0x9f, 0xf3, 0x7d, 0xe7,
	0x3b, 0x3f, 0x01, 0x18, 0x8e, 0x29, 0xef, 0x25, 0x69, 0xcc, 0x63, 0xb2, 0x26, 0xbe, 0x3b, 0x0f,
	0x47, 0x71, 0x3c, 0x0a, 0xf0, 0x50, 0xda, 0x6e, 0x26, 0x5f, 0x0f, 0xb9, 0x1f, 0x22, 0xe3, 0x34,
	0x4c, 0xb2, 0x67, 0x4e, 0x0b, 0x36, 0xce, 0xc2, 0x84, 0x7f, 0xbf, 0x40, 0xc6, 0xe8, 0x08, 0x9d,
	0x6b, 0xd8, 0xbe, 0xc4, 0xa9, 0x3a, 0xb9, 0xf8, 0x6d, 0x82, 0x8c, 0x13, 0x02, 0x6b, 0x13, 0x86,
	0x69, 0xbb, 0xd2, 0xad, 0x1c, 0x34, 0x5d, 0xf9, 0x2d, 0x6c, 0x21, 0x86, 0x71, 0xbb, 0x9a, 0xd9,
	0xc4, 0x37, 0x69, 0xc3, 0xfa, 0x70, 0x4c, 0xa3, 0x08, 0x83, 0x76, 0x4d, 0x9a, 0xf5, 0xd1, 0xb9,
	0x02, 0x72, 0xe6, 0xf9, 0xbc, 0x10, 0xb7, 0x05, 0x55, 0xdf, 0x93, 0x51, 0x2d, 0xb7, 0xea, 0x7b,
	0x4b, 0x63, 0xee, 0x41, 0x1d, 0x3d, 0x9f, 0xa3, 0x27, 0x43, 0x36, 0x5c, 0x75, 0x72, 0x06, 0x92,
	0xe8, 0x69, 0x16, 0xdf, 0x20, 0x1a, 0xd1, 0x10, 0x35, 0x51, 0xf1, 0x4d, 0xba, 0x60, 0x7b, 0xc8,
	0x86, 0xa9, 0x9f, 0x70, 0x3f, 0x8e, 0x54, 0x6c, 0xd3, 0x44, 0x76, 0xc0, 0x8a, 0xa7, 0x11, 0xa6,
	0x8a, 0x74, 0x76, 0x70, 0x92, 0x8c, 0x72, 0x01, 0x61, 0x09, 0x65, 0x89, 0x58, 0x2d, 0x47, 0xac,
	0xad, 0x40, 0x5c, 0x33, 0x11, 0x27, 0xd0, 0xba, 0xc4, 0xe9, 0x35, 0xc3, 0x74, 0x55, 0x3e, 0x3b,
	0x60, 0x61, 0x48, 0xfd, 0x40, 0x41, 0x66, 0x07, 0xd2, 0x81, 0x46, 0x42, 0x19, 0x9b, 0xc6, 0xa9,
	0xa7, 0x00, 0xf3, 0x33, 0x79, 0x00, 0xe0, 0x87, 0x74, 0x84, 0x83, 0x84, 0xf2, 0xb1, 0x82, 0x6c,
	0x4a, 0xcb, 0x15, 0xe5, 0x63, 0xe7, 0x67, 0x05, 0x36, 0x45, 0xa6, 0x26, 0xf0, 0x3e, 0x34, 0xe2,
	0xc0, 0x1b, 0x18, 0xe0, 0xeb, 0x71, 0xe0, 0x5d, 0x96, 0xe3, 0x6b, 0xa6, 0x35, 0x83, 0xe9, 0x23,
	0xd8, 0x10, 0x41, 0x72, 0x5e, 0x19, 0xb2, 0x1d, 0x07, 0xde, 0x95, 0xa6, 0x66, 0xd2, 0xb6, 0xe6,
	0x69, 0x8b, 0x02, 0x9c, 0xa3, 0xd6, 0x9f, 0xa9, 0xd6, 0xf9, 0xaf, 0x05, 0xf8, 0x04, 0xf7, 0x0c,
	0x44, 0x17, 0x59, 0x12, 0x47, 0x0c, 0xc9, 0x0b, 0x68, 0xa8, 0x3e, 0x66, 0xed, 0x4a, 0xb7, 0x76,
	0x60, 0xf7, 0xdb, 0x3d, 0x39, 0x69, 0x8b, 0xf4, 0xdc, 0xfc, 0xa5, 0x73, 0x01, 0x9b, 0xe7, 0x28,
	0x45, 0xfd, 0x27, 0xee, 0x7b, 0x50, 0xa7, 0xb7, 0x94, 0x53, 0xdd, 0x8d, 0xea, 0xe4, 0xbc, 0x85,
	0x2d, 0x1d, 0x2e, 0x27, 0xf6, 0x04, 0x2c, 0x31, 0x8b, 0x9a, 0xd5, 0x6e, 0xce, 0xca, 0x44, 0x75,
	0xb3, 0x37, 0x4e, 0x4f, 0xca, 0xa9, 0x8c, 0x4c, 0x17, 0xda, 0x18, 0xd9, 0xca, 0xfc, 0xc8, 0x5e,
	0x40, 0xe7, 0x1c, 0xf9, 0x07, 0x3f, 0xe0, 0x98, 0xa2, 0x77, 0x67, 0x3f, 0xb2, 0x0b, 0xf5, 0xd0,
	0x8f, 0x06, 0xbe, 0x27, 0xd3, 0xb2, 0x5c, 0x2b, 0xf4, 0xa3, 0x8f, 0x9e, 0xf3, 0xab, 0x32, 0x87,
	0xbf, 0x42, 0x92, 0xbb, 0xaf, 0x15, 0xf2, 0x0a, 0x9a, 0xf9, 0x42, 0x93, 0xa5, 0xb4, 0xfb, 0x9d,
	0x5e, 0xb6, 0xf2, 0x7a, 0x7a, 0xe5, 0xf5, 0xbe, 0xe8, 0x17, 0xee, 0xec, 0x71, 0xbe, 0xd2, 0x2c,
	0x63, 0xa5, 0xcd, 0xa4, 0xaf, 0x9b, 0xd2, 0x1b, 0x2b, 0x68, 0x7d, 0x6e, 0x05, 0xdd, 0xc8, 0x76,
	0x99, 0x29, 0x33, 0x6b, 0x97, 0x50, 0xd9, 0x16, 0xda, 0xa5, 0x90, 0xbe, 0x9b, 0xbf, 0x2c, 0x93,
	0xad, 0x07, 0x5b, 0x27, 0x69, 0x4c, 0xbd, 0x21, 0x65, 0x5c, 0x6b, 0xdf, 0x81, 0x86, 0xe0, 0x6b,
	0x0c, 0x67, 0x7e, 0x76, 0x7e, 0x57, 0x61, 0xdb, 0x70, 0x50, 0x94, 0x8e, 0x60, 0x43, 0x30, 0x18,
	0x28, 0x34, 0xe9, 0xb5, 0x8a, 0x96, 0x2d, 0x2e, 0x74, 0x89, 0xfa, 0x33, 0xf9, 0xab, 0x05, 0xbf,
	0x62, 0xf7, 0xe7, 0x85, 0x79, 0xac, 0xe4, 0xad, 0x49, 0x87, 0x92, 0xc6, 0xcc, 0x54, 0x7f, 0xaa,
	0x9b, 0x38, 0xab, 0xdf, 0xde, 0xfc, 0x5b, 0x9d, 0x82, 0xea, 0x62, 0xf2, 0x1e, 0xb6, 0xcd, 0x4c,
	0x06, 0xa2, 0x14, 0xb2, 0x88, 0x39, 0xad, 0xc5, 0xff, 0x8c, 0xbb, 0x69, 0xa4, 0x23, 0xae, 0x95,
	0x1e, 0x82, 0x69, 0x16, 0xa0, 0x5e, 0x0c, 0x30, 0xbf, 0xf5, 0xa5, 0x1e, 0xe2, 0x2c, 0xae, 0xfa,
	0x3f, 0x2c, 0xb0, 0x4f, 0xc7, 0x94, 0x7f, 0xc6, 0xf4, 0xd6, 0x1f, 0x22, 0x79, 0x03, 0xcd, 0x5c,
	0x71, 0xa2, 0xe8, 0x17, 0x6b, 0xd6, 0xb9, 0xbf, 0x60, 0xcf, 0xf2, 0x7a, 0x56, 0x21, 0xc7, 0xd0,
	0x3a, 0x0d, 0x62, 0x86, 0x7f, 0x0f, 0x42, 0x14, 0x41, 0xe3, 0x87, 0x4d, 0x5e, 0x03, 0xbc, 0xf3,
	0xf4, 0x78, 0x12, 0x05, 0xb3, 0xf0, 0x0b, 0x5f, 0xe1, 0xaa, 0x52, 0x35, 0x5c, 0xe7, 0x93, 0x5f,
	0xea, 0x7a, 0x04, 0xb6, 0xa1, 0x33, 0x29, 0x95, 0x7e, 0x95, 0xb3, 0x06, 0x2e, 0x95, 0x7d, 0xa9,
	0xf3, 0x31, 0xd8, 0x46, 0xe3, 0x91, 0x25, 0x4f, 0x3a, 0xfb, 0x0b, 0xfd, 0x99, 0x0f, 0xc2, 0x4b,
	0x68, 0xe8, 0xce, 0x5a, 0xea, 0x5a, 0xd2, 0x7d, 0xe4, 0x44, 0xa2, 0xea, 0x31, 0x21, 0x8b, 0x93,
	0xa3, 0x29, 0xef, 0x2f, 0xb9, 0x51, 0x31, 0x5c, 0xb9, 0x2e, 0x8a, 0x0b, 0x95, 0x74, 0x73, 0x8f,
	0x92, 0x5d, 0xbb, 0x22, 0xe6, 0x4d, 0x5d, 0x6e, 0xb9, 0xe7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xa1, 0x10, 0xc8, 0x30, 0xfa, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	// broadcast
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (ChatService_BroadcastClient, error)
	CloseBroadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	// add new object
	AddMessage(ctx context.Context, in *NewMessageRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	AddChannel(ctx context.Context, in *NewChannelRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	// edit object
	EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	EditChannel(ctx context.Context, in *EditChannelRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	// get object
	GetChannels(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetChannelsResponse, error)
	GetUsers(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetUsersResponse, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	GetFilteredMessages(ctx context.Context, in *GetFilteredMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (ChatService_BroadcastClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatService_serviceDesc.Streams[0], "/chat.ChatService/Broadcast", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceBroadcastClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_BroadcastClient interface {
	Recv() (*BroadcastResponse, error)
	grpc.ClientStream
}

type chatServiceBroadcastClient struct {
	grpc.ClientStream
}

func (x *chatServiceBroadcastClient) Recv() (*BroadcastResponse, error) {
	m := new(BroadcastResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) CloseBroadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/chat.ChatService/CloseBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) AddMessage(ctx context.Context, in *NewMessageRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/chat.ChatService/AddMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) AddChannel(ctx context.Context, in *NewChannelRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/chat.ChatService/AddChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) EditMessage(ctx context.Context, in *EditMessageRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/chat.ChatService/EditMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) EditChannel(ctx context.Context, in *EditChannelRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/chat.ChatService/EditChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetChannels(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetChannelsResponse, error) {
	out := new(GetChannelsResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatService/GetChannels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetUsers(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatService/GetMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetFilteredMessages(ctx context.Context, in *GetFilteredMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/chat.ChatService/GetFilteredMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	// broadcast
	Broadcast(*BroadcastRequest, ChatService_BroadcastServer) error
	CloseBroadcast(context.Context, *BroadcastRequest) (*EmptyMessage, error)
	// add new object
	AddMessage(context.Context, *NewMessageRequest) (*EmptyMessage, error)
	AddChannel(context.Context, *NewChannelRequest) (*EmptyMessage, error)
	// edit object
	EditMessage(context.Context, *EditMessageRequest) (*EmptyMessage, error)
	EditChannel(context.Context, *EditChannelRequest) (*EmptyMessage, error)
	// get object
	GetChannels(context.Context, *EmptyMessage) (*GetChannelsResponse, error)
	GetUsers(context.Context, *EmptyMessage) (*GetUsersResponse, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	GetFilteredMessages(context.Context, *GetFilteredMessagesRequest) (*GetMessagesResponse, error)
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) Broadcast(req *BroadcastRequest, srv ChatService_BroadcastServer) error {
	return status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (*UnimplementedChatServiceServer) CloseBroadcast(ctx context.Context, req *BroadcastRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseBroadcast not implemented")
}
func (*UnimplementedChatServiceServer) AddMessage(ctx context.Context, req *NewMessageRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMessage not implemented")
}
func (*UnimplementedChatServiceServer) AddChannel(ctx context.Context, req *NewChannelRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChannel not implemented")
}
func (*UnimplementedChatServiceServer) EditMessage(ctx context.Context, req *EditMessageRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditMessage not implemented")
}
func (*UnimplementedChatServiceServer) EditChannel(ctx context.Context, req *EditChannelRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditChannel not implemented")
}
func (*UnimplementedChatServiceServer) GetChannels(ctx context.Context, req *EmptyMessage) (*GetChannelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannels not implemented")
}
func (*UnimplementedChatServiceServer) GetUsers(ctx context.Context, req *EmptyMessage) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedChatServiceServer) GetMessages(ctx context.Context, req *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (*UnimplementedChatServiceServer) GetFilteredMessages(ctx context.Context, req *GetFilteredMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilteredMessages not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Broadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BroadcastRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).Broadcast(m, &chatServiceBroadcastServer{stream})
}

type ChatService_BroadcastServer interface {
	Send(*BroadcastResponse) error
	grpc.ServerStream
}

type chatServiceBroadcastServer struct {
	grpc.ServerStream
}

func (x *chatServiceBroadcastServer) Send(m *BroadcastResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_CloseBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CloseBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/CloseBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CloseBroadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/AddMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AddMessage(ctx, req.(*NewMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_AddChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AddChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/AddChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AddChannel(ctx, req.(*NewChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_EditMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).EditMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/EditMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).EditMessage(ctx, req.(*EditMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_EditChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).EditChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/EditChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).EditChannel(ctx, req.(*EditChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetChannels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetChannels(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetUsers(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetFilteredMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilteredMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetFilteredMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/GetFilteredMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetFilteredMessages(ctx, req.(*GetFilteredMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseBroadcast",
			Handler:    _ChatService_CloseBroadcast_Handler,
		},
		{
			MethodName: "AddMessage",
			Handler:    _ChatService_AddMessage_Handler,
		},
		{
			MethodName: "AddChannel",
			Handler:    _ChatService_AddChannel_Handler,
		},
		{
			MethodName: "EditMessage",
			Handler:    _ChatService_EditMessage_Handler,
		},
		{
			MethodName: "EditChannel",
			Handler:    _ChatService_EditChannel_Handler,
		},
		{
			MethodName: "GetChannels",
			Handler:    _ChatService_GetChannels_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _ChatService_GetUsers_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _ChatService_GetMessages_Handler,
		},
		{
			MethodName: "GetFilteredMessages",
			Handler:    _ChatService_GetFilteredMessages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Broadcast",
			Handler:       _ChatService_Broadcast_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}
