// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js"
// @generated from file chat.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BroadcastRequest, BroadcastResponse, DeleteChannelRequest, DeleteMessageRequest, EditChannelRequest, EditMessageRequest, EmptyMessage, GetChannelsResponse, GetFilteredMessagesRequest, GetMessagesRequest, GetMessagesResponse, GetUsersResponse, NewChannelRequest, NewMessageRequest } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chat.ChatService
 */
export const ChatService = {
  typeName: "chat.ChatService",
  methods: {
    /**
     * broadcast
     *
     * @generated from rpc chat.ChatService.Broadcast
     */
    broadcast: {
      name: "Broadcast",
      I: BroadcastRequest,
      O: BroadcastResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc chat.ChatService.CloseBroadcast
     */
    closeBroadcast: {
      name: "CloseBroadcast",
      I: BroadcastRequest,
      O: EmptyMessage,
      kind: MethodKind.Unary,
    },
    /**
     * add new object
     *
     * @generated from rpc chat.ChatService.AddMessage
     */
    addMessage: {
      name: "AddMessage",
      I: NewMessageRequest,
      O: EmptyMessage,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.AddChannel
     */
    addChannel: {
      name: "AddChannel",
      I: NewChannelRequest,
      O: EmptyMessage,
      kind: MethodKind.Unary,
    },
    /**
     * delete object
     *
     * @generated from rpc chat.ChatService.DeleteMessage
     */
    deleteMessage: {
      name: "DeleteMessage",
      I: DeleteMessageRequest,
      O: EmptyMessage,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.DeleteChannel
     */
    deleteChannel: {
      name: "DeleteChannel",
      I: DeleteChannelRequest,
      O: EmptyMessage,
      kind: MethodKind.Unary,
    },
    /**
     * edit object
     *
     * @generated from rpc chat.ChatService.EditMessage
     */
    editMessage: {
      name: "EditMessage",
      I: EditMessageRequest,
      O: EmptyMessage,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.EditChannel
     */
    editChannel: {
      name: "EditChannel",
      I: EditChannelRequest,
      O: EmptyMessage,
      kind: MethodKind.Unary,
    },
    /**
     * get object
     *
     * @generated from rpc chat.ChatService.GetChannels
     */
    getChannels: {
      name: "GetChannels",
      I: EmptyMessage,
      O: GetChannelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.GetUsers
     */
    getUsers: {
      name: "GetUsers",
      I: EmptyMessage,
      O: GetUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.GetMessages
     */
    getMessages: {
      name: "GetMessages",
      I: GetMessagesRequest,
      O: GetMessagesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.GetFilteredMessages
     */
    getFilteredMessages: {
      name: "GetFilteredMessages",
      I: GetFilteredMessagesRequest,
      O: GetMessagesResponse,
      kind: MethodKind.Unary,
    },
  }
};

