// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=js"
// @generated from file auth.proto (package auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EmptyMessage, LoginRequest, LoginResponse, RegisterRequest } from "./auth_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service auth.AuthService
 */
export const AuthService = {
  typeName: "auth.AuthService",
  methods: {
    /**
     * @generated from rpc auth.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.Refresh
     */
    refresh: {
      name: "Refresh",
      I: EmptyMessage,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
  }
};

