// @generated by protoc-gen-es v2.11.0 with parameter "target=js"
// @generated from file auth.proto (package auth, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file auth.proto.
 */
export const file_auth = /*@__PURE__*/
  fileDesc("CgphdXRoLnByb3RvEgRhdXRoIg4KDEVtcHR5TWVzc2FnZSIyCgxMb2dpblJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiNQoNTG9naW5SZXNwb25zZRIUCgxhY2Nlc3NfdG9rZW4YASABKAkSDgoGYXZhdGFyGAIgASgJIkQKD1JlZ2lzdGVyUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCTKrAQoLQXV0aFNlcnZpY2USMAoFTG9naW4SEi5hdXRoLkxvZ2luUmVxdWVzdBoTLmF1dGguTG9naW5SZXNwb25zZRIyCgdSZWZyZXNoEhIuYXV0aC5FbXB0eU1lc3NhZ2UaEy5hdXRoLkxvZ2luUmVzcG9uc2USNgoIUmVnaXN0ZXISFS5hdXRoLlJlZ2lzdGVyUmVxdWVzdBoTLmF1dGguTG9naW5SZXNwb25zZWIGcHJvdG8z");

/**
 * Describes the message auth.EmptyMessage.
 * Use `create(EmptyMessageSchema)` to create a new message.
 */
export const EmptyMessageSchema = /*@__PURE__*/
  messageDesc(file_auth, 0);

/**
 * Describes the message auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema = /*@__PURE__*/
  messageDesc(file_auth, 1);

/**
 * Describes the message auth.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema = /*@__PURE__*/
  messageDesc(file_auth, 2);

/**
 * Describes the message auth.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema = /*@__PURE__*/
  messageDesc(file_auth, 3);

/**
 * @generated from service auth.AuthService
 */
export const AuthService = /*@__PURE__*/
  serviceDesc(file_auth, 0);

